### ISSUE TITLE
Vols en avion

### ISSUE THREAD

**Issue by publicodes** [laem/futureco-data#28]
Le calcul des émissions d'un vol en avion est très complexe. Voir le lien wikipedia ci-dessous pour s'en rendre compte.

En particulier, il me semble que vou n'avez pas pris en compte le forçage radiatif... qui est sujet à débat mais qui multiplie l'impact d'un vol en avion par quelque chose comme 2.7.

> "These CO2 emissions are generally into the high atmosphere, and this is thought to have a greater greenhouse effect than CO2 released at sea level. The emissions are therefore adjusted by multiplication by a factor of 2.00 (see 'Radiative forcing' below) to give 180 kg CO2 equivalent per hour."

Voir ces liens : 
- https://www.carbonindependent.org/sources_aviation.html
- https://fr.m.wikipedia.org/wiki/Impact_climatique_du_transport_aérien

**Comment by laem** [comment]
Résolu essentiellement par #30
