### ISSUE TITLE
Entretenir une pelouse

### ISSUE THREAD

**Issue by laem** [laem/futureco-data#40]
L'impact d'une pelouse parfait peut être énorme !

https://www.semanticscholar.org/paper/The-effects-of-household-management-practices-on-of-Gu-Crane/399fa763c6050c6912a0d7bd58becf525194bb4a

Etude résumée semble-t-il ici : http://palebluedot.llc/carbon-copy/2015/7/16/the-carbon-footprint-of-a-lawn?&ampcf=1.

Cet article doit permettre un premier modèle assez simple et parlant.

**Comment by pascoual** [comment]
J'ai commencé, tu préfères que je clone ou donner des droits pour créer une branche ?

**Comment by laem** [comment]
Je t'ai donné les droits :)

**Comment by pascoual** [comment]
J'ai publié deux calcules dans la branche jardin :
- mon jardin
- une tonte
Mais comme l'appli est orientée journée tu veux que je dé-publie "mon jardin" ?

**Comment by laem** [comment]
Génial, j'en ai fait une PR #82. 
Je n'ai pas encore eu le temps de lire / tester. Tu as pu le tester en local chez toi via les instructions de CONTRIBUTING ? 

> Mais comme l'appli est orientée journée tu veux que je dé-publie "mon jardin" ?

Non pas de souci. Pour l'instant la branche ` journée` n'est pas en ligne, et le reste des simulations pourra parler de n'importe quelle période.

**Comment by pascoual** [comment]
Oui oui j'ai testé en local.

**Comment by laem** [comment]
C'est génial @pascoual , merci pour cet ajout :)

**Comment by pascoual** [comment]
Justement j'en avais besoin hier et j'ai du démarrer l'env de dev ;) !

**Comment by laem** [comment]
D'ailleurs, je vais bientôt permettre la création d'une "branche de démo" pour chaque PR ici sur futureco-data. C'était permis uniquement pour futureco, pour l'instant.
