### ISSUE TITLE
Vol aller-retour ne fonctionne plus

### ISSUE THREAD

**Issue by The-Minh** [laem/futureco-data#80]
Cette page ne charge pas

https://futur.eco/simulateur/transport/avion/impact

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/2910722/80968661-a5c91700-8e18-11ea-9c46-19511eb72626.png">

**Comment by laem** [comment]
Oups, je regarde ça dès que possible :) 
C'est un sujet d'actualité

**Comment by laem** [comment]
Bon, problème complexe, car en ouvrant le lien dans une fenêtre de navigation privée je n'ai pas le souci

**Comment by laem** [comment]
Autre hypothèse : j'ai enlevé le service worker, peut-être que les navigateurs qui l'avaient enregistrés sont "bloqués".

**Comment by laem** [comment]
En attendant de trouver mieux @The-Minh tu peux faire Ctrl-F5 pour rafraichir en invalidant le cache

**Comment by laem** [comment]
Je ferme car ce problème sera réglé par l'expiration des caches des navigateurs.
